image: node:8

stages:
  - test

test_unit:
  stage: test
  script:
    - npm install
    - npm run test:unit

eslint:
  stage: test
  script:
    - npm install
    -  ./node_modules/.bin/eslint src/**